version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - echo "Entered the pre-build phase"
      - echo "Login to AWS ECR"
      - aws --version
      - SERVICE_NAME=common
      - REPOSITORY_URI=271609209442.dkr.ecr.us-east-2.amazonaws.com/oreo/$SERVICE_NAME
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo "Entered build phase"
      - DATE=$(date +%Y%m%d%H%M)
      - ./mvnw clean package -DskipTests=true
      - docker build -t oreo/oreo-gateway:v1 .
      - docker tag $REPOSITORY_URI:sit-$DATE $REPOSITORY_URI:$RELEASE_TAG
      - docker push $REPOSITORY_URI:sit-$DATE
  post_build:
    commands:
      - echo "post notifications"
